import '@fontsource/material-icons'
import '@fontsource/roboto'
import '@mdi/font/css/materialdesignicons.min.css'
import 'bootstrap/dist/css/bootstrap-grid.min.css'
import './src/styles/global.css'
import './src/styles/index.scss'